config/routes.rb
Rails.application.routes.draw do
  get 'events/show'
  get 'events/new'
  get 'events/index'
  root 'events#index'
  devise_for :users
  resources :events, except: [:destroy, :edit, :update]
  resources :users, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
    validates :start_date, :duration, :title, :description, :price, :location, presence: :true
    validate :cant_be_past
    validate :duration_5_pos
    validates :title, length: { in: 5..140}
    validates :description, length: { in: 20..1000 }
    validate :price_validation
    belongs_to :admin, class_name: 'User'
    has_many :attendances
    has_many :users, through: :attendances
  
    def self.convert_date_time(date, time)
      (date.to_s + " " +time.to_s).to_datetime
    end
  
    private 
    
    def cant_be_past
      if start_date.nil?
        errors.add(:start_date, "must be filled") 
      else
        errors.add(:start_date, "cant be past") if start_date < Time.now
      end
    end
    
    def duration_5_pos
      if duration.nil?
        errors.add(:duration, "must be filled") 
      else
        errors.add(:duration, "has to be a multiple of 5") unless duration % 5 == 0
        errors.add(:duration, "has to be a positive amount of minutes") unless duration > 0
      end
    end
  
    def price_validation
      if price.nil?
        errors.add(:price, "must be filled") 
      else
        errors.add(:price, "cant be free") if price < 1
        errors.add(:price, "cant be over 1000") if price > 1000
      end
    end
  end
  

app/models/profile.rb
class Profile < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.start_date = Event.convert_date_time(params[:date], params[:hour])
    @event.admin = current_user
    puts event_params
    if @event.save
      redirect_to @event
    else 
      @date = params[:date]
      @hour = params[:hour]
      render :new
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :location, :price, :duration)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/index.html.erb
<br>
<br>
<center>
<div class="card text-center" style="width: 50rem;">
  <div class="card-header">
    MyProfile
  </div>
  <div class="card-body">
  <% if user_signed_in? %>
    <h4 class="card-title">Here is your email : <%= current_user.email %></h4>
    <p class="card-text"><%= link_to "Edit email / password", edit_user_registration_path %></p>
    <div class="btn-group">
    <%= link_to "Sign out", destroy_user_session_path, method: :delete, class:"btn btn-sm btn-primary" %>
  </div>
    <% else %>
    <%= link_to "Log In", new_user_session_path, class:"btn btn-sm btn-primary"  %>
    <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-sm btn-primary"  %>
    <% end %>
  </div>
</div>
</center>

app/views/events/new.html.erb
<h1>Events#new</h1>
<p>Find me in app/views/events/new.html.erb</p>

app/views/events/show.html.erb
<div class="jumbotron text-center text-white">
  <h2 class="display-5">Welcome to</h2>
  <h1 class="display-3">Eventbrite</h1>
  <br>
  <p class="lead">Quickly find events near you & create your new events here :</p> 
  
    <a class="btn btn-primary btn-lg" href="<%= events_new_path %>" role="button">Create New Event</a>
  </p>
</div>

app/views/home/index.html.erb
# <div class="jumbotron text-center text-white">
#   <h4 class="display-4">Welcome to</h4>
#   <h1 class="display-3">Eventbrite</h1>
#   <br>
#   <p class="lead">quickly find events near you & create your new events here :</p> 
  
#     <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
#   </p>
# </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <title>Eventbrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= events_show_path %>">Eventbrite</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
      <a class="nav-link" href="<%= events_show_path %>">All Events<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="<%= events_new_path %>">Create New Event</a>
      </li>
    </ul>
  </div>
  <% unless user_signed_in? %>
  <li class="nav-item dropdown text-black bg-light">
    <a class="nav-link dropdown-toggle text-black bg-light" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Sign Up/Log In
    </a>
    <div class="dropdown-menu bg-primary text-black bg-light" aria-labelledby="navbarDropdownMenuLink">
      <a class="dropdown-item text-black bg-light" href="<%= new_user_registration_path %>">Sign Up</a>
      <a class="dropdown-item text-black bg-light" href="<%= new_user_session_path %>">Log In</a>
    </div>
  </li>
<% else %>
  <li class="nav-item dropdown text-black bg-light">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      My Profile
    </a>
    <div class="dropdown-menu bg-primary text-black bg-light" aria-labelledby="navbarDropdownMenuLink">
    <a class="dropdown-item text-black bg-light" href="<%= user_session_path %>">My Profile</a>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"dropdown-item"%>
    </div>
  </li>
<% end %>
</ul>
</div>
</nav>
</nav>
    <%= yield %>

  </body>
</html>
<a href=""></a>